query {
  card(id: $card_id$) {
    pipe {
      id
      name
    }
    id
    title
    created_at
    createdBy {
      id
      name
      email
    }
    due_date

    current_phase {
      id
      name
    }
  }
}