query{
  phase(id: $phase_id$) {
    cards(after: $after$) {
      edges {
        node {
          id
          created_at
          fields {
            field {
              id
              label
              options
            }
            value
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}