query{
  phase(id: $phase_id$) {
    cards(after: $after$) {
      edges {
        node {
          id
          title
          created_at
          createdBy {
            id
            name
          }
          due_date
          current_phase {
            id
            name
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}